version: '2'

services:

  mysql:
    image: mysql:5.6
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
       - "3706:3306"
    extends:
     file: environment.yml
     service: environment_vars
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

  graphql:
    image: "mhart/alpine-node:8.10"
    working_dir: /src
    command: "npm run start"
    extends:
     file: environment.yml
     service: environment_vars
    volumes:
      - ../../:/src
      - ./tmp/log:/log
    ports:
      - "3780:80"
    environment:
      - PORT=80
      - PUBLIC_GRAPHQL_URL=http://localhost:3780/graphql

  web:
    image: "mhart/alpine-node"
    working_dir: /src
    command: "npm run start:dev"
    extends:
     file: environment.yml
     service: environment_vars
    volumes:
      - ../../website:/src
    ports:
      - "3788:3788"
    environment:
      - PORT=3788
      - PUBLIC_GRAPHQL_URL=http://localhost:3780/graphql

